# Server
server:
  port: 8000

spring:
  # Secret
  profiles:
    active: db
  # Mysql
  datasource:
    url: ${url}
    username: ${adminname}
    password: ${password}
    driver-class-name: ${driver-class-name}
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# Swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
