# Server
server:
  port: 8000

spring:
  # Secret
  profiles:
    active: db
  # Mysql
  datasource:
    url: ${url}
    username: ${adminname}
    password: ${password}
    driver-class-name: ${driver-class-name}
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true         # All Sql show
        format_sql: true       # sql pretty show
        use_sql_comments: true # /* */ within the Sql show
        highlight_sql: true    # colorful


logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace       # Parameters show


# Swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
