# Server
server:
  port: 8002

spring:
  # SECRET
  profiles:
    active: test
  # MYSQL
  datasource:
    url: ${url}
    username: ${adminname}
    password: ${password}
    driver-class-name: ${driver-class-name}
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  # 404 Error
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  #### h2
  h2:
    console:
      enabled: ${h2}

# LOGGING
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

## USER SERVER BASE URL
user.server.base.url: ${user-server-url}

# Swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


