server:
  port: 80

spring:
  profiles:
    active: dev

  #### datasource
  datasource:
    driver-class-name: ${driver-class-name}
    url: ${url}
    username: ${username}
    password: ${password}

  #### h2
  h2:
    console:
      enabled: ${h2}

#### mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml

#### logging
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

#### Swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
