url: jdbc:mysql://db-i9fap-kr.vpc-pub-cdb.ntruss.com:3306/user_test?useUnicode=true&characterEncoding=UTF-8&characterSetResult=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
adminname: master
password: eventty!123
driver-class-name: com.mysql.cj.jdbc.Driver

---
h2: false
