#### mysql
driver-class-name: com.mysql.cj.jdbc.Driver
url: jdbc:mysql://db-i9fap-kr.vpc-pub-cdb.ntruss.com:3306/event_dev?useUnicode=true&characterEncoding=UTF-8&characterSetResult=UTF-8&serverTimezone=Asia/Seoul
#jdbc:mysql://127.0.0.1:3306/eventty_business_dev
username: master
password: eventty!123
h2: false