## jwt
issuer: eventty
secret_key: eventtyKey

## server URI
user_server: userservice
auth_server: authservice
event_server: businessservice

## server url
user-server-url: http://userservice:8000
auth-server-url: http://authservice:8002
event-server-url: http://eventservice:80
