server:
  port: 8001

spring:
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: user-authorization
          uri: http://${user_server}:8000/
          predicates:
            - Path=/api/user/secret/**
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/user/secret/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie

        - id: user-not-authorization
          uri: http://${user_server}:8000/
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie

        - id: event-authorization
          uri: http://${event_server}:80/
          predicates:
            - Path=/api/event/secret/**
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/event/secret/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie

        - id: event-not-authorization
          uri: http://${event_server}:80/
          predicates:
            - Path=/api/event/**
          filters:
            - RewritePath=/api/event/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie

        - id: auth-authorization
          uri: http://${auth_server}:8002/
          predicates:
            - Path=/api/auth/secret/**
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/auth/secret/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie

        - id: auth-not-authorization
          uri: http://${auth_server}:8002/
          predicates:
            - Path=/api/auth/**
          filters:
          - RewritePath=/api/auth/(?<segment>.*), /$\{segment}
          - RemoveRequestHeader=Cookie

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://${frontend_server}:3000"
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
            allowCredentials: true

## JWT
jwt.secret_key: ${secret_key}
jwt.issuer: ${issuer}

## SERVER BASE URL
server.base.url.user_server: ${user-server-url}
server.base.url.auth_server: ${auth-server-url}
server.base.url.event_server: ${event-server-url}


