server:
  port: 8001

spring:
  cloud:
    gateway:
      routes:
        - id: userservice-server
          # ?? URL (??? http://userservice:8000/ ?? ??)
          uri: http://userservice:8000/
          predicates:
            - Path=/api/users/**
        - id: event-server
          # ?? URL (??? http://eventservice:8000/ ?? ??)
          uri: http://businessservice:80/
          predicates:
            - Path=/api/events/**
        - id: auth-server
          uri: http://localhost:8002/
          predicates:
            - Path=/api/auth/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE



