version: "3.9"
services:
  frontend:
    image: hyk0/eventty_front:latest
    command: npm start
    container_name: Frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/front/node_modules
      - ./frontend:/app/front
    networks:
      eventty:
        aliases:
          - "front server"
  businessservice:
    image: serin0404/event:1.7
    container_name: Event_Server
    build:
      context: ./businessservice
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./businessservice:/src/businessservice
    networks:
      eventty:
        aliases:
          - "event server"
  userservice:
    image: hyungyunk/eventty:1.7
    container_name: User_Server
    build:
      context: ./userservice
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./userservice:/src/userservice
    networks:
      eventty:
        aliases:
          - "user server"
  authservice:
    image: auth:2.0
    container_name: Auth_Server
    build:
      context: ./authservice
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./authservice:/src/authservice
    networks:
      eventty:
        aliases:
          - "auth server"
  gateway:
    image: gateway:1.8
    container_name: Gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./gateway:/src/gateway
    networks:
      eventty:
        aliases:
          - "gateway server"
  applyservice:
    image: hyungyunk/apply:1.7
    container_name: Apply_Server
    build:
      context: ./applyservice
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - ./applyservice:/src/applyservice
    networks:
      eventty:
        aliases:
          - "apply server"
networks:
  eventty:
    driver: bridge
